### ISSUE TITLE
As a developer my API component should use  a Cloudant instance as the wallet for my keys 

### ISSUE THREAD

**Issue by mayarobin** [IBM-Blockchain-Starter-Kit/api-bootstrap#2]
Allow User to specify the name of the cloudant instance that should be used by the api component. If the instance does not exist, the pipeline should create it, if it does, we should leverage it.

**Comment by eymorale** [comment]
Closing this in favor of certificate manager, plus the flexibility of a developer using whatever wallet they want. The fabric sdk's couchdb wallet already works with Cloudant
