### ISSUE TITLE
As a developer I should be able to get a scaffolding project for the API component of a Blockchain MVP

### ISSUE THREAD

**Issue by yorhodes** [IBM-Blockchain-Starter-Kit/api-bootstrap#6]
Baseline Capabilities:
* proper logging (library)
* basic API for ping invoke
* basic API for health check
* proper directory structure for model/controller/routes

Advanced Capabilities:
* Leverage API Connect in cloud foundry service
* Secure API authentication

**Comment by eymorale** [comment]
Work In Progress is here: https://github.com/eymorale/api-bootstrap

**Comment by eymorale** [comment]
I think this one is done. Advanced capabilities will be captured in other issues
